# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82447a88e6ec2180bd5b4770a89f026f5e162fd3487aa0f6c4a11fde6f444ab3502cbed9afd718466be117a89c77ef00647420f9bf4473c2ff0e51a3ae6dd0ee

test:
  secret_key_base: cd50ae214905512941ba19c9788b870c57288afce46a8dbe4a9cd38886b46dab4df78dbf8d76f5e5319c7e583e3ab83f522ead3d42608e78baecbf6d90b35e74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
